name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: false

      - name: Install dependencies
        run: yarn --prefer-offline

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Build
        run: yarn build
